# This file was generated by GoReleaser. DO NOT EDIT.
cask "telegram-owl" do
  version "2.1.0"

  on_macos do
    on_intel do
      sha256 "bd7b3c6b06960fc4fc3dc43795cad7e02ea688123bd52745d1fdd437f3390a62"
      url "https://github.com/beeyev/telegram-owl/releases/download/v#{version}/telegram-owl_v#{version}_macOS_64bit.tar.gz"
    end
    on_arm do
      sha256 "75011627fd9453929edc57e30f92a2d2461fbf489afd669b17a5f868d4db58e9"
      url "https://github.com/beeyev/telegram-owl/releases/download/v#{version}/telegram-owl_v#{version}_macOS_ARM64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0c555bd0dfcf558e070d259a72f682045252125e4bdca813784220d8fbb1b80f"
      url "https://github.com/beeyev/telegram-owl/releases/download/v#{version}/telegram-owl_v#{version}_Linux_64bit.tar.gz"
    end
    on_arm do
      sha256 "03950a97d27f8f4ee25b7b66acb621b8fbb001acef322cd3a28b76aeb658b406"
      url "https://github.com/beeyev/telegram-owl/releases/download/v#{version}/telegram-owl_v#{version}_Linux_ARM64.tar.gz"
    end
  end

  name "telegram-owl"
  desc "CLI utility to send messages and files to Telegram chats and channels"
  homepage "https://github.com/beeyev/telegram-owl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "telegram-owl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/telegram-owl"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    run 'telegram-owl --help' to get started
  EOS
end
