# This file was generated by GoReleaser. DO NOT EDIT.
cask "telegram-owl" do
  version "1.5.0"

  on_macos do
    on_intel do
      sha256 "edd7308014c116d5c381b08bd7b5f2759df8c719f35d4dcd9d56d3ddfe9146c7"
      url "https://github.com/beeyev/telegram-owl/releases/download/v#{version}/telegram-owl_v#{version}_macOS_64bit.tar.gz"
    end
    on_arm do
      sha256 "7140e46385803a1a0dd92b325663682ac3bf89c35ff51b2447fff62872bdfb0c"
      url "https://github.com/beeyev/telegram-owl/releases/download/v#{version}/telegram-owl_v#{version}_macOS_ARM64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d319e31b24432093a0a4a31159acb69c96773ad1004ac026024d5a7603f29d8f"
      url "https://github.com/beeyev/telegram-owl/releases/download/v#{version}/telegram-owl_v#{version}_Linux_64bit.tar.gz"
    end
    on_arm do
      sha256 "73b1dc93a79b3b79190136243cdb61e796832da547fbac16e5977aadfac9d29f"
      url "https://github.com/beeyev/telegram-owl/releases/download/v#{version}/telegram-owl_v#{version}_Linux_ARM64.tar.gz"
    end
  end

  name "telegram-owl"
  desc "CLI utility to send messages and files to Telegram chats and channels"
  homepage "https://github.com/beeyev/telegram-owl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "telegram-owl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/telegram-owl"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    run 'telegram-owl --help' to get started
  EOS
end
