# This file was generated by GoReleaser. DO NOT EDIT.
cask "telegram-owl" do
  version "2.0.1"

  on_macos do
    on_intel do
      sha256 "f3f61109fbb08f6e31b14bdf0b56945fdf4de75df906df008f217b2c5a2f0041"
      url "https://github.com/beeyev/telegram-owl/releases/download/v#{version}/telegram-owl_v#{version}_macOS_64bit.tar.gz"
    end
    on_arm do
      sha256 "f6d7b1f644a83c847ab5a01f523d1050ec5198981f53863f9fb06d40356a3a2e"
      url "https://github.com/beeyev/telegram-owl/releases/download/v#{version}/telegram-owl_v#{version}_macOS_ARM64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c00b3e948e79a9a6c1cfc84f177f5ea01ac222f985969d152e26f58a7f5f100f"
      url "https://github.com/beeyev/telegram-owl/releases/download/v#{version}/telegram-owl_v#{version}_Linux_64bit.tar.gz"
    end
    on_arm do
      sha256 "140d88e2e97264db49484f489b2d7c47b935dbfe4acaf4d32ecd59803f085330"
      url "https://github.com/beeyev/telegram-owl/releases/download/v#{version}/telegram-owl_v#{version}_Linux_ARM64.tar.gz"
    end
  end

  name "telegram-owl"
  desc "CLI utility to send messages and files to Telegram chats and channels"
  homepage "https://github.com/beeyev/telegram-owl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "telegram-owl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/telegram-owl"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    run 'telegram-owl --help' to get started
  EOS
end
