# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TelegramOwl < Formula
  desc "CLI utility to send messages and files to Telegram chats and channels"
  homepage "https://github.com/beeyev/telegram-owl"
  version "1.3.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/beeyev/telegram-owl/releases/download/v1.3.3/telegram-owl_v1.3.3_macOS_64bit.tar.gz"
      sha256 "e83fac6094d7f4ee4f51e7fde942602723e0c25c1d75e69f205622be80a8e0b0"

      def install
        bin.install "telegram-owl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/beeyev/telegram-owl/releases/download/v1.3.3/telegram-owl_v1.3.3_macOS_ARM64.tar.gz"
      sha256 "67457c7ad03d977b66d8f09d433d8ce67ba1d75894c1aba3941953d96a1fd9e7"

      def install
        bin.install "telegram-owl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/beeyev/telegram-owl/releases/download/v1.3.3/telegram-owl_v1.3.3_Linux_64bit.tar.gz"
        sha256 "84c936e08b2e8207511349da46bc9403085a70db317f46d6476e01da54ff7739"

        def install
          bin.install "telegram-owl"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/beeyev/telegram-owl/releases/download/v1.3.3/telegram-owl_v1.3.3_Linux_ARM.tar.gz"
        sha256 "beba8c15eb2bec9ef9114cc96f6e11ec3d8afa135a04aef78dc3c273bc03f945"

        def install
          bin.install "telegram-owl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/beeyev/telegram-owl/releases/download/v1.3.3/telegram-owl_v1.3.3_Linux_ARM64.tar.gz"
        sha256 "700b601b7d7bc19afe2b9bb218ad116503851bfee7f02147cf2c2f8fa552e137"

        def install
          bin.install "telegram-owl"
        end
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/telegram-owl --version")
  end
end
