# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TelegramOwl < Formula
  desc "CLI utility to send messages and files to Telegram chats and channels"
  homepage "https://github.com/beeyev/telegram-owl"
  version "1.3.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/beeyev/telegram-owl/releases/download/v1.3.3/telegram-owl_v1.3.3_macOS_64bit.tar.gz"
      sha256 "004049518e8f5f26776316afb54517d777866172b64446da897f60f07b5f8dd9"

      def install
        bin.install "telegram-owl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/beeyev/telegram-owl/releases/download/v1.3.3/telegram-owl_v1.3.3_macOS_ARM64.tar.gz"
      sha256 "901074b67e61b02c50b53591f0f37bc8f0be9acef4cc65392b67873e71329217"

      def install
        bin.install "telegram-owl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/beeyev/telegram-owl/releases/download/v1.3.3/telegram-owl_v1.3.3_Linux_64bit.tar.gz"
        sha256 "1a5382e23676ec4495755e5e650b2d37dc705cfe1194fcc7dc29b6fb43d1ba8d"

        def install
          bin.install "telegram-owl"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/beeyev/telegram-owl/releases/download/v1.3.3/telegram-owl_v1.3.3_Linux_ARM.tar.gz"
        sha256 "fdd7cea62d195b7be297c7807127e2111bbc39edacfc78b298c568ee1b2493d0"

        def install
          bin.install "telegram-owl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/beeyev/telegram-owl/releases/download/v1.3.3/telegram-owl_v1.3.3_Linux_ARM64.tar.gz"
        sha256 "35a31b9ffcfe69d3c0812924b8b31e20d1e81ef43f10f3f1eb9051d8fb6b236c"

        def install
          bin.install "telegram-owl"
        end
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/telegram-owl --version")
  end
end
